// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApwUjJ4ZmQE4zzewbyv8CZdGHlzVaIOp0',
    appId: '1:1050509503275:web:8f9e35a8028c814223336e',
    messagingSenderId: '1050509503275',
    projectId: 'spotify-ob7jv',
    authDomain: 'spotify-ob7jv.firebaseapp.com',
    storageBucket: 'spotify-ob7jv.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNtvXuBWdntYk0jNGKL5awMLKmx1a3YjU',
    appId: '1:1050509503275:android:5a79ef9910fe1b5323336e',
    messagingSenderId: '1050509503275',
    projectId: 'spotify-ob7jv',
    storageBucket: 'spotify-ob7jv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsXgWkZDo8lwZHEfwddfsPzH992QcV1Q0',
    appId: '1:1050509503275:ios:041e589ee9eb40e823336e',
    messagingSenderId: '1050509503275',
    projectId: 'spotify-ob7jv',
    storageBucket: 'spotify-ob7jv.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsXgWkZDo8lwZHEfwddfsPzH992QcV1Q0',
    appId: '1:1050509503275:ios:041e589ee9eb40e823336e',
    messagingSenderId: '1050509503275',
    projectId: 'spotify-ob7jv',
    storageBucket: 'spotify-ob7jv.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApwUjJ4ZmQE4zzewbyv8CZdGHlzVaIOp0',
    appId: '1:1050509503275:web:6901403777f3101923336e',
    messagingSenderId: '1050509503275',
    projectId: 'spotify-ob7jv',
    authDomain: 'spotify-ob7jv.firebaseapp.com',
    storageBucket: 'spotify-ob7jv.appspot.com',
  );
}
